spring.application.name=espcar
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== MQTT CONFIG =====
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=spring-espcar-server
mqtt.username=
mqtt.password=

mqtt.keep-alive=60
mqtt.qos=1
mqtt.clean-session=true

# topic base
mqtt.topic.base=devices